domain: api_gateway
descriptors:
- key: path_minute
  value: GET:/pets
  rate_limit:
    unit: minute
    requests_per_unit: 5
- key: path_hour
  value: GET:/pets
  rate_limit:
    unit: hour
    requests_per_unit: 20
- key: path_minute
  value: POST:/pets
  rate_limit:
    unit: minute
    requests_per_unit: 3
- key: path_hour
  value: POST:/pets
  rate_limit:
    unit: hour
    requests_per_unit: 10
- key: path_minute
  value: GET:/pets/{id}
  rate_limit:
    unit: minute
    requests_per_unit: 8
- key: path_hour
  value: GET:/pets/{id}
  rate_limit:
    unit: hour
    requests_per_unit: 30
- key: path_minute
  value: DELETE:/pets/{id}
  rate_limit:
    unit: minute
    requests_per_unit: 3
- key: path_hour
  value: DELETE:/pets/{id}
  rate_limit:
    unit: hour
    requests_per_unit: 10
- key: path_minute
  value: GET:/pets/{id}/vaccinations
  rate_limit:
    unit: minute
    requests_per_unit: 5
- key: path_hour
  value: GET:/pets/{id}/vaccinations
  rate_limit:
    unit: hour
    requests_per_unit: 20
